## Business Python Final Exam Information  
Please complete these problems to the best of your abilities. You may use any and all resources at your disposal, but are expected to work individually -- this should be reflected in your code. Significant partial credit will be awarded for attempted solutions that are the product of well-documented effort. Show the full range of your attempts, write comments to explain your logic, and document any research that you do. Learning to program isn't about remembering syntax or knowing how to solve a problem on the first try, it is more about refining your ability to reason through a process, persisting and trying multiple approaches, and using resources effectively to guide you towards a solution. I keep this in mind when reviewing your work. I will be available to clarify questions as needed, but to be fair, will refrain from giving away too much information to any single student. Best of luck and thank-you for your hard work!

**Problem 1: String Operations**  
Write a program that accepts a string of the form:
```
'$45.21,$62.15,$565.02,$789.98'
```
and splits it into a list of floats with no ```$``` symbols.  Given the string above as an input, your program should return,
```
[45.21, 62.15, 565.02, 789.98]
```
and have a list data type.  

In [1]:
def convert_data(s):
    # YOUR CODE
    converted= map(float, string.split("$"))
    print(converted)

Run the function and check the output

In [ ]:
string='$45.21,$62.15,$565.02,$789.98'
convert_data(string)

Expected Output
```
[45.21, 62.15, 565.02, 789.98]
```

**Problem 2:  Data Structures**
You work for a manufacturer, and have been asked to calculate the total profit made on the sales of a collection of products. You are given a list of dictionaries each of which contains the product name, cost price per unit (in dollars), sell price per unit (in dollars), and the starting inventory. Write a function called ```profit()``` that returns a new dictionary in which the keys are the product names and the values are the total profit found using the formula ```inventory * (sell_price - cost_price)```.

Examples:
```
products=[
{
    "product":"Mini Drone",
    "cost_price": 2.04,
    "sell_price": 6.95,
    "inventory": 1500
},
{
    "product":"3D puzzle",
    "cost_price": 1.68,
    "sell_price": 5.95,
    "inventory": 6000
},
{
    "product":"Origami Paper",
    "cost_price": 2.77,
    "sell_price": 7.95,
    "inventory": 8500
},
{
    "product":"Night Vision Goggles",
    "cost_price": 3.57,
    "sell_price": 9.95,
    "inventory": 3000
}
]
```
Expected Output
```
{'3D puzzle': 25620,
 'Mini Drone': 7365,
 'Night Vision Goggles': 19140,
 'Origami Paper': 44030}
```


In [ ]:
def profit(dct):
    # YOUR CODE


Run the function and test the output

In [ ]:
# Test:
products=[
{
    "product":"Mini Drone",
    "cost_price": 2.04,
    "sell_price": 6.95,
    "inventory": 1500
},
{
    "product":"3D puzzle",
    "cost_price": 1.68,
    "sell_price": 5.95,
    "inventory": 6000
},
{
    "product":"Origami Paper",
    "cost_price": 2.77,
    "sell_price": 7.95,
    "inventory": 8500
},
{
    "product":"Night Vision Goggles",
    "cost_price": 3.57,
    "sell_price": 9.95,
    "inventory": 3000
}
]



profit(products)

Expected Output
```
{'3D puzzle': 25620,
 'Mini Drone': 7365,
 'Night Vision Goggles': 19140,
 'Origami Paper': 44030}
 ```

**Problem 3.  Numpy Arrays and Operations**    
The goal of this exercise is to analyze top baseball player salaries in the National and American leagues using numpy. The data has the form shown below. See source: -https://www.baseball-reference.com/leaders/Salary_leagues.shtml.  The values in the columns, are ```'year', 'NL top salary', 'AL top salary'```

```
data=[[2019, 42143000, 36833333],
      [2018, 35571429, 34083000],
      [2017, 35571429, 30000000],
      [2016, 34571429,30000000,],
      [2015, 32571429, 28000000]]
```
a. Create a Numpy Array using the data as the input.

b. Write a program to determine (and output) the increase in both NL top salaries and in AL top salaries in the last 5 years.   

c. Write a program to determine whether the top salary was greater in the AL or the NL. Output a statement communicating the direction of the difference and also the value of the difference between the NL and the AL top salary in each of the last 5 years.

In [ ]:
def baseball(data):
    import numpy as np
    # a create the numpy array
    # YOUR CODE

    # b determine the change in top salary over the last 5 years
    # YOUR CODE

    # c determine the year to year difference in salary between AL and NL
    # YOUR CODE


Run the function and check the output


In [ ]:
salaries=[
    [2021, 40000000, 37116667],
    [2020, 35920616, 37666666],
    [2019, 38333333, 36833333],
    [2018, 35571429, 34083000],
    [2017, 35571429,30000000]]

baseball(salaries)

Expected Output
```
[[    2021 40000000 37116667]
 [    2020 35920616 37666666]
 [    2019 38333333 36833333]
 [    2018 35571429 34083000]
 [    2017 35571429 30000000]]


NL salaries increased by 4428571 over the last five years
AL salaries increased by 7666666 over the last five years


NL > AL by 2883333
AL > NL by 1746050
NL > AL by 1500000
NL > AL by 1488429
NL > AL by 5571429
```

## Problem 4. Pandas Data_Reader with World Bank
This function should extract data from the World Bank api and perform some analysis. The function parameters are the indicator, a list of countries, a starting year and an ending year. Fill in the code to complete the program.  
  
[World Bank Remote Data Access documentation](https://pandas-datareader.readthedocs.io/en/latest/readers/world-bank.html)    
[List of Country Codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes)

a. Use the download function to acquire the data from the WB servers by indicator and country.

b. Create a pivot table summarizing the GDP per capita.

c. Create the time series plot of the pivot table.   

In [ ]:
# # installing dependencies
# # this only has to be run once per session, you can comment it out thereafter
! pip install pandas-datareader # comment out after running once


In [ ]:
def get_world_data(ct_list, ind, start_date, end_date):
    import pandas as pd
    import matplotlib.pyplot as plt
    from pandas_datareader import wb

    # run the code to examine the indicator names and symbols
    mathces = wb.search('gdp.*capita.*const')
    # print the results to see the indicator names and symbols
    print(mathces)

    # a. use the download function to acquire the data from the WB servers by indicator and country
    # YOUR CODE

    #b. Create a pivot table summarizing the indicator, ind, by country and by year with years as the rows (index) and columns as the countries
    # YOUR CODE

    # c. Create the time series plot of the pivot table
    # YOUR CODE

Run the function and check the output

In [ ]:
# Run the function
COUNTRIES=['US', 'CA', 'FR','DE','IT','GB','JP']
INDICATOR='NY.GDP.PCAP.KD'
START=2000
END=2020

get_world_data(COUNTRIES, INDICATOR, START, END)

Expected Output
```
                        id  ...            topics
716      6.0.GDPpc_constant  ...  Economy & Growth
10384        NY.GDP.PCAP.KD  ...  Economy & Growth
10386        NY.GDP.PCAP.KN  ...  Economy & Growth
10388     NY.GDP.PCAP.PP.KD  ...  Economy & Growth
10389  NY.GDP.PCAP.PP.KD.87  ...                  

[5 rows x 7 columns]
              NY.GDP.PCAP.KD
country year                
Canada  2020        42108.17
        2019        44958.09
        2018        44765.50
        2017        44325.42
        2016        43536.91
country    Canada    France   Germany  ...     Japan  United Kingdom  United States
year                                   ...                                         
2000     34121.61  33583.86  34476.21  ...  31430.63        38450.22       48689.03
2001     34227.34  34001.70  34996.99  ...  31476.05        39348.27       48690.81
2002     35015.79  34138.63  34869.03  ...  31416.12        40035.72       49081.36
2003     36024.10  34176.56  34605.74  ...  31830.22        41173.49       50053.62
2004     37086.45  34885.84  35019.99  ...  32515.12        41875.90       51476.49

[5 rows x 7 columns]
```

![image](https://drive.google.com/uc?id=1OkdYl9IHbwJueo5i7obg2HY0ntAFfIEG)

**Problem 5: Data Summary and Visualization**
In this problem, we perform some of the preliminary tasks of a statistical modeling exercise.  We will use a data set that contains measurements for basketball player salaries (response variable) for a collection of highly paid players along with explanatory variables potentially related to salary. The function below will perform some of the steps of a linear regression analysis.





#### a. Build the dataframe
Connect to the data url and create the pandas dataframe using the code provided below and perform some preprocessing tasks.

#### b. Statistical Summary
Use a pandas method to generate a statistical summary of all the variables in the dataframe.

#### c. Pairwise scatterplots and histogram
Use the pairplot method to generate the graphic to visualize the individual distributions and the pairwise scatterplots.

#### d. Correlation Matrix
Calculate the correlations and create a heatmap to visualize them.

#### e. Linear Regression
Fit a linear model to the data using all of the variables.
```
'salary ~ rating+height+age+time_since_draft+college_ind'
```


In [ ]:
def basketball_analysis(url):
    import pandas as pd
    import requests
    from io import StringIO
    # libraries for data visualization
    import matplotlib.pyplot as plt
    import seaborn as sns
    # libraries for statistical modeling
    import pandas.util.testing as tm
    import statsmodels.formula.api as smf

    # a. Build the dataframe
    file_id = url.split('/')[-2]
    dwn_url='https://drive.google.com/uc?export=download&id=' + file_id
    url = requests.get(dwn_url).text
    csv_raw = StringIO(url)
    basketball = pd.read_csv(csv_raw)

    # Examine the first 6 lines of the data frame
    header=basketball.head()
    print(header, '\n')

    # List and print the variable names
    # YOUR CODE

    # b. Generate and print a statistical summary
    # YOUR CODE

    # c. Generate a pairwise scatterplot of the quantitative variables.
    # First, create a new data frame using the quantitative variables: 'rating','height','age','time_since_draft','salary'
    # YOUR CODE

    # d. Calculate the correlations and create a heatmap (use plt.figure() prior to running the code to create the heatmap)
    # YOUR CODE
    # plt.figure() # uncomment prior to running heatmap



    # e. Fit a linear model
    # use smf.ols function to generate the linear model (ordinary least squares regression)
    # YOUR CODE

    # inspect the results with the summary() method
    # YOUR CODE




In [ ]:
# Run the function (no function argument)
orig_url="https://drive.google.com/file/d/17oAYo3H5GfQR3LEUv5cXuuH1yK4GX80B/view?usp=sharing"
basketball_analysis(orig_url)

Expected Output
```
   Unnamed: 0              full_name  ... rating      salary
0           0           LeBron James  ...     97  37436858.0
1           1          Kawhi Leonard  ...     97  32742000.0
2           2  Giannis Antetokounmpo  ...     96  25842697.0
3           3           Kevin Durant  ...     96  37199000.0
4           4           James Harden  ...     96  38199000.0

[5 rows x 10 columns]

Index(['Unnamed: 0', 'full_name', 'team', 'position', 'height', 'college_ind',
       'time_since_draft', 'age', 'rating', 'salary'],
      dtype='object')

       Unnamed: 0      height  ...      rating        salary
count  429.000000  429.000000  ...  429.000000  4.290000e+02
mean   214.000000    1.995641  ...   76.372960  8.530080e+06
std    123.985886    0.083514  ...    5.657748  9.218059e+06
min      0.000000    1.750000  ...   67.000000  5.000000e+04
25%    107.000000    1.930000  ...   72.000000  2.000000e+06
50%    214.000000    2.010000  ...   75.000000  4.380120e+06
75%    321.000000    2.060000  ...   79.000000  1.220000e+07
max    428.000000    2.240000  ...   97.000000  4.023176e+07

[8 rows x 7 columns]

                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 salary   R-squared:                       0.655
Model:                            OLS   Adj. R-squared:                  0.651
Method:                 Least Squares   F-statistic:                     160.8
Date:                Sun, 21 Nov 2021   Prob (F-statistic):           1.95e-95
Time:                        21:24:00   Log-Likelihood:                -7259.6
No. Observations:                 429   AIC:                         1.453e+04
Df Residuals:                     423   BIC:                         1.456e+04
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept        -8.067e+07   8.66e+06     -9.313      0.000   -9.77e+07   -6.36e+07
rating            1.123e+06   5.25e+04     21.377      0.000    1.02e+06    1.23e+06
height            -2.03e+06   3.27e+06     -0.620      0.536   -8.47e+06    4.41e+06
age               2.031e+05   1.71e+05      1.190      0.235   -1.32e+05    5.39e+05
time_since_draft  3.807e+05   1.89e+05      2.019      0.044    1.01e+04    7.51e+05
college_ind       4.884e+05   7.83e+05      0.624      0.533   -1.05e+06    2.03e+06
==============================================================================
Omnibus:                       13.983   Durbin-Watson:                   1.804
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               24.275
Skew:                           0.190   Prob(JB):                     5.36e-06
Kurtosis:                       4.102   Cond. No.                     2.78e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.78e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
```
![image](https://drive.google.com/uc?id=1Pd8abqENDl6NdVRTed77PFlTE9qjvoZH)

![image](https://drive.google.com/uc?id=1hmqGdoBtLgUHn84xsx21c2puZe2z_yT1)